### ISSUE TITLE
hello_world lesson fails on verify

### ISSUE THREAD

**Issue by chrisstahl** [maxogden/elementary-electron#11]
It looks like this line is causing the failure:

fsCheck(path.join('.', 'index.js')),

The instructions tell you to create an index.html file. I may do a pull later today to fix.

**Comment by tanem** [comment]
@chrisstahl #9 is already open to fix this.

**Comment by gyaresu** [comment]
I just downloaded 1.3.5 from npm and it's still broken. 

I commented on the PR as I'm not sure why master here is only at 1.3.4
https://github.com/maxogden/elementary-electron/pull/9#issuecomment-230631515

**Comment by Benmhz** [comment]
Note that the test code only checks for the existence of these files. No actual code is tested. 
I simply made sure electron would run my app, and made an empty 'index.js' file to earn the clear.
