### ISSUE TITLE
HelloWorld. No browser window opens. 

### ISSUE THREAD

**Issue by KeithKiely** [maxogden/elementary-electron#12]
Ubuntu 16.04
Node version v6.2.2 
npm version 3.10.2.
Electron version 1.2.3 (most recent version tried also)
Browser doesn't open and when I run verify it's missing the index.js.

I´ve ran it on my windows laptop and it works fine so must be OS related.

**Comment by tanem** [comment]
@KeithKiely:

> when I run verify it's missing the index.js.

#9 is open to fix this.

**Comment by danfinlay** [comment]
PR #9 fixed this
