### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by Togame-san** [maxogden/elementary-electron#13]
It (the glitch) seems to me that the automation for verification is lacking. In particular, the lesson entitled 'Hello World' directs the user to generate a simple HTML file (index.html) and a javascript file (app.js); however, the verification just requires the presence of a html.JS and an app.js for a successful pass. Evenmoreso, the resulting run does not appear to work but passes the verification. 

-M

**Comment by tanem** [comment]
Pending fix in #9.
